# Generated by Django 4.2.28 on 2026-02-25 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_universitysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit-Based'), ('need', 'Need-Based'), ('full', 'Full Scholarship'), ('partial', 'Partial Scholarship'), ('sports', 'Sports'), ('arts', 'Arts & Culture'), ('research', 'Research'), ('government', 'Government / National'), ('other', 'Other')], max_length=20)),
                ('coverage', models.CharField(choices=[('full_tuition', 'Full Tuition'), ('partial_tuition', 'Partial Tuition'), ('living', 'Living Expenses'), ('tuition_living', 'Tuition + Living Expenses'), ('research', 'Research Funding'), ('other', 'Other')], max_length=20)),
                ('stipend_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stipend_unknown', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('no_deadline', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=2000)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, help_text='Note to the submitter (visible to them)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
